src/AppBundle/Entity/Commission.php
<?php

    namespace AppBundle\Entity;

    use AppBundle\DataObject\SumarizationDataObject;
    use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\ORM\Mapping as ORM;

    /**
     * Commission
     *
     * @ORM\Table(name="Commission")
     * @ORM\Entity(repositoryClass="AppBundle\Entity\CommissionRepository")
     */
    class Commission extends AbstractCommissionHierarchy
    {
        /**
         * @var integer
         *
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;

        /**
         * @var string
         *
         * @ORM\Column(name="name_own", type="string", length=255, nullable=true)
         */
        private $nameOwn;

        /**
         * @var string
         *
         * @ORM\Column(name="description", type="text", nullable=true)
         */
        private $description;

        /**
         * @var string
         *
         * @ORM\Column(name="status", type="string", length=255, nullable=true)
         */
        private $status;

        /**
         * @var \DateTime
         *
         * @ORM\Column(type="datetime")
         */
        private $created;

        /**
         * @var Campaign
         *
         * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Campaign", inversedBy="commissions")
         * @ORM\JoinColumn(referencedColumnName="id", onDelete="CASCADE")
         */
        private $campaign;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\CommissionUserCompanyRelation", mappedBy="commission", cascade={"persist"})
         */
        private $commissionUserCompanyRelations;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\Subcommission", mappedBy="commission")
         */
        private $subcommissions;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\Budget", mappedBy="commission")
         */
        private $budgets;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\Timesheet", mappedBy="commission")
         */
        private $timesheets;

        /**
         * @var boolean
         *
         * @ORM\Column(type="boolean")
         */
        private $lockedForTimesheets = false;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\FavouriteCommission", mappedBy="commission")
         */
        private $favouriteCommissions;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\Cost", mappedBy="commission")
         */
        private $costs;

        /**
         * @var File
         * @ORM\OneToOne(targetEntity="AppBundle\Entity\File", cascade={"persist"})
         * @ORM\JoinColumn(name="file_id", referencedColumnName="id")
         */
        private $image;

        /**
         * @var \DateTime
         *
         * @ORM\ManyToOne(targetEntity="AppBundle\Entity\YearMonth")
         * @ORM\JoinColumn(referencedColumnName="id")
         */
        private $startDate;

        /**
         * @var \DateTime
         *
         * @ORM\ManyToOne(targetEntity="AppBundle\Entity\YearMonth")
         * @ORM\JoinColumn(referencedColumnName="id")
         */
        private $endDate;

        /**
         * @var bool
         *
         * @ORM\Column(name="client_approved", type="boolean")
         */
        private $clientApproved = false;

        /**
         * @var bool
         *
         * @ORM\Column(name="billable", type="boolean")
         */
        private $billable = true;

        /**
         * @var bool
         *
         * @ORM\Column(name="repeatable", type="boolean")
         */
        private $repeatable = false;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\AllocationContainer", mappedBy="commission",
         *                                                                     cascade={"persist"})
         */
        private $allocationContainers;

        /**
         * @var string
         *
         * @ORM\Column(name="name", type="string", length=255)
         */
        private $name;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\AllocationUnit", mappedBy="commission", cascade={"persist"})
         */
        private $allocationUnits;

        /**
         * @var ArrayCollection
         *
         * @ORM\OneToMany(targetEntity="AppBundle\Entity\InvoiceItem", mappedBy="commission", cascade={"persist",
         *                                                             "remove"})
         */
        private $invoiceItems;

//    /**
//     * @var SumarizationDataObject
//     */
//    private $sums;
//
//    /**
//     * @return SumarizationDataObject
//     */
//    public function getSums(){
//        return $this->sums;
//    }
//
//    /**
//     * @param SumarizationDataObject $sums
//     */
//    public function setSums( $sums ){
//        $this->sums = $sums;
//    }

        public function getInvoiceItemsSum(){
            $items = array_filter($this->getInvoiceItems()->toArray(), function($entry){
                return ($entry->getEnabled()) ? true : false;
            });
            $sum = 0;
            /** @var InvoiceItem $item */
            foreach($items as $item){
                $sum = $sum+$item->getPrice();
            }
            return $sum;
        }

        public function getSums(){

            $array = [];

            /** @var AllocationContainer $item */
            foreach($this->getAllocationContainers() as $item){
                if($item->getEnabled() && $item->getClientApproved()){
                    $array[] = $item->getSums();
                }
            }

            $sums = new AllocationsContainerSums();
            $sums->sumarize($array);
            $sums->setInvoicePrice($this->getInvoiceItemsSum());

//        if($sums->getInvoicePrice() > 0){
//            dump($sums);exit;
//        }

            return $sums;

        }

        public function getNetIncome(){

            $costsBuyingReal = 0;
            $costsSellingReal = 0;

            /** @var AllocationContainer $allocationContainer */
            foreach($this->getAllocationContainers() as $allocationContainer){
                if($allocationContainer->getClientApproved() and $allocationContainer->getEnabled()){
                    /** @var AllocationContainerList $allocationContainerList */
                    foreach($allocationContainer->getAllocationContainerLists() as $allocationContainerList){
                        /** @var AllocationContainerListItem $allocationContainerListItem */
                        foreach($allocationContainerList->getAllocationContainerListItems() as $allocationContainerListItem){
                            if($allocationContainerListItem->getExternalSource()){
                                $costsBuyingReal = $costsBuyingReal + $allocationContainerListItem->getBuyingPriceReal()*$allocationContainerListItem->getQuantityReal();
                                $costsSellingReal = $costsSellingReal + $allocationContainerListItem->getSellingPriceReal()*$allocationContainerListItem->getQuantityReal();
                            }
                        }
                    }
                }
            }

            $r = $this->getInvoiceItemsSum()-$costsBuyingReal+$costsSellingReal;

            return $r;

        }

        public function getHourlyRate(){

            $sum = 0.1;

            $timesheets = $this->getTimesheets();
            /** @var Timesheet $timesheet */
            foreach($timesheets as $timesheet){
                $sum = $sum + $timesheet->getDuration();
            }

            return round($this->getInvoiceItemsSum()/($sum/60));

        }

        public function getHourPlanVsReal(){

            $sumHr = 0.1;

            $timesheets = $this->getTimesheets();
            /** @var Timesheet $timesheet */
            foreach($timesheets as $timesheet){
                $sumHr = $sumHr + $timesheet->getDuration();
            }

            $sumHp = 0.1;
            $allocationUnits = $this->getAllocationUnits();
            /** @var AllocationUnit $allocationUnit */
            foreach($allocationUnits as $allocationUnit){
                $sumHp = $sumHp + $allocationUnit->getHoursPlan();
            }

            return round(($sumHr/60-$sumHp)/($sumHp)*100);

        }

        public function getCompany(){

            return $this->getCampaign()->getClient()->getCompany();

        }

        /**
         * @return string
         */
        public function generateName(){
            $i = $this->campaign->getCommissions()->count()+1;
            $i = str_pad($i, 3, '0', STR_PAD_LEFT);
            return $this->campaign->getName().$i;
        }


        /**
         * Vrátí všechny subzakázky zakázky v definovaném časovém okně
         *
         * @param \AppBundle\Entity\TimeWindow $timeWindow
         *
         * @return \Doctrine\Common\Collections\Collection
         */
        public function getSubcommissionsInTimeWindow(TimeWindow $timeWindow){

            return $this->getSubcommissions()->filter(
                function($entry) use ($timeWindow) {
                    $id = $entry->getYearmonth()->getId();
                    return ($id <= $timeWindow->getYearmonthTo()->getId() and $id >= $timeWindow->getYearmonthFrom()->getId());
                }
            );

        }

        /**
         * Vrátí poslední subzakázku
         *
         * @return mixed
         */
        public function getLastSubcommission(){

            return $this->getSubcommissions()->last();

        }

src/AppBundle/Controller/InvoiceController.php
<?php

namespace AppBundle\Controller;
use AppBundle\DependencyInjection\CommissionManager\CommissionManager;
use AppBundle\Entity\InvoiceItem;
use AppBundle\Form\Type\InvoiceItemFormType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

/**
 * Allocation controller.
 */
class InvoiceController extends BaseController
{
    /**
     * @Route("/commission/{commission_id}/invoice-item/list")
     * @Template()
     */
    public function listAction($commission_id){

        $em = $this->getDoctrine()->getManager();

        $commission = $em->getRepository('AppBundle:Commission')->find($commission_id);

        if(!$commission){
            $this->addFlash('danger', 'Tato zakázka neexistuje.');
            return $this->redirectToRoute('app_client_list');
        }

        $user = $this->getUser();

        $cm = new CommissionManager($em);
        $commissionWhereParticipate = $cm->getCommissionsWhereParticipate($user);
        $check = in_array($commission, $commissionWhereParticipate, true);

        if(!$check){
            $this->addFlash('danger', 'K této zakázce nemáte přístup.');
            return $this->redirectToRoute('app_client_list');
        }

        $criteria = [
            'commission' => $commission,
            'enabled' => true,
        ];
        $orderBy = [
            'created' => 'ASC'
        ];
        $entities = $em->getRepository('AppBundle:InvoiceItem')->findBy($criteria, $orderBy);

        $data = [
            'entities' => $entities,
            'commission2' => $commission,
            'commission' => [
                'data' => $commission
            ]
        ];

        return $data;

    }

    /**
     * @Route("/commission/{commission_id}/invoice-item/create")
     * @Template()
     */
    public function createAction($commission_id, Request $request){

        $em = $this->getDoctrine()->getManager();

        $commission = $em->getRepository('AppBundle:Commission')->find($commission_id);

        if(!$commission){
            $this->addFlash('danger', 'Tato zakázka neexistuje.');
            return $this->redirectToRoute('app_client_list');
        }

        $user = $this->getUser();

        $cm = new CommissionManager($em);
        $commissionWhereParticipate = $cm->getCommissionsWhereParticipate($user);
        $check = in_array($commission, $commissionWhereParticipate, true);

        if(!$check){
            $this->addFlash('danger', 'K této zakázce nemáte přístup.');
            return $this->redirectToRoute('app_client_list');
        }

        $entity = new InvoiceItem();
        $entity->setEnabled(true);
        $entity->setCommission($commission);
        $entity->setAuthor($user);
        $entity->setCreated(new \DateTime());

        $form = $this->getForm($entity);

        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form->isValid()){
                $em->persist($entity);
                $em->flush();

                $this->addFlash('success', 'Položka k fakturaci byla vytvořena.');
                $params = [
                    'commission_id' => $commission_id
                ];
                return $this->redirectToRoute('app_invoice_list', $params);
            }else{
                $this->addFlash('danger', 'Položka k fakturaci nebyla vytvořena.');
            }
        }

        $data = [
            'form' => $form->createView(),
            'commission' => $commission,
        ];

        return $data;

    }

    /**
     * @Route("/invoice-item/{invoiceItem_id}/update")
     * @Template()
     */
    public function updateAction($invoiceItem_id, Request $request){

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:InvoiceItem')->find($invoiceItem_id);

        if(!$entity){
            $this->addFlash('danger', 'Tato položka k fakturaci neexistuje.');
            return $this->redirectToRoute('app_client_list');
        }

        $commission = $entity->getCommission();

        $user = $this->getUser();

        $cm = new CommissionManager($em);
        $commissionWhereParticipate = $cm->getCommissionsWhereParticipate($user);
        $check = in_array($commission, $commissionWhereParticipate, true);

        if(!$check){
            $this->addFlash('danger', 'K této zakázce nemáte přístup.');
            return $this->redirectToRoute('app_client_list');
        }

        $form = $this->getForm($entity);

        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form->isValid()){
                $em->persist($entity);
                $em->flush();

                $this->addFlash('success', 'Položka k fakturaci byla upravena.');
                $params = [
                    'commission_id' => $commission->getId(),
                ];
                return $this->redirectToRoute('app_invoice_list', $params);
            }else{
                $this->addFlash('danger', 'Položka k fakturaci nebyla upravena.');
            }
        }

        $data = [
            'form' => $form->createView(),
            'commission' => $commission,
        ];

        return $data;

    }

    /**
     * @Route("/invoice-item/{invoiceItem_id}/delete")
     */
    public function deleteAction($invoiceItem_id){

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:InvoiceItem')->find($invoiceItem_id);

        if(!$entity){
            $this->addFlash('danger', 'Tato položka k fakturaci neexistuje.');
            return $this->redirectToRoute('app_client_list');
        }

        $commission = $entity->getCommission();

        $user = $this->getUser();

        $cm = new CommissionManager($em);
        $commissionWhereParticipate = $cm->getCommissionsWhereParticipate($user);
        $check = in_array($commission, $commissionWhereParticipate, true);

        if(!$check){
            $this->addFlash('danger', 'K této zakázce nemáte přístup.');
            return $this->redirectToRoute('app_client_list');
        }

        $entity->setEnabled(false);
        $em->persist($entity);
        $em->flush();

        $this->addFlash('success', 'Položka k fakturaci byla odstraněna.');
        $params = [
            'commission_id' => $entity->getCommission()->getId(),
        ];

        return $this->redirectToRoute('app_invoice_list', $params);


    }

    /**
     * @param \AppBundle\Entity\InvoiceItem $entity
     *
     * @return \Symfony\Component\Form\Form
     */
    private function getForm(InvoiceItem $entity){

        $type = new InvoiceItemFormType();

        $form = $this->createForm($type, $entity);

        return $form;

    }
}

src/AppBundle/Resources/views/Invoice/create.html.twig
{% extends "::layout-secured-simple.html.twig" %}
{% set title = "Vytvoření položky k fakturaci pro " ~ commission.name %}
{% block title %}{{ title }} {{ titleSeparator }} {{ parent() }}{% endblock %}
{% block body_class %}page-budget-create {{ parent() }}{% endblock %}

{% block content %}


        <div class="row">

            <div class="col-lg-12">
                <a class="btn btn-info" title="Zpět" href="{{ path('app_invoice_list', {'commission_id': commission.id}) }}"><i class="fa fa-fw fa-caret-left"></i> Zpět</a>

                <div class="page-header text-center">
                    <h2><i class="fa fa-fw fa-money"></i> {{ title }}</h2>
                </div>
            </div> <!-- .col-lg-12 -->


            {% include "@App/Invoice/inc/form.html.twig" with {"form" : form, "submitLabel" : "Vytvořit"} %}


        </div> <!-- .row -->


{% endblock %}

src/AppBundle/Resources/views/Invoice/list.html.twig
{% extends '::layout-secured.html.twig' %}

{% set title = commission.data.name %}
{% block title %}{{ title }} {{ titleSeparator }} {{ parent() }}{% endblock %}
{% block body_class %}page-commission-detail{{ parent() }}{% endblock %}

{% block content %}

<!-- ========== Page header ========== -->
{% include '@App/Commission/inc/commissionHeader.html.twig' with {'commission' : commission, 'label' : 'přehled'} %}

<style>
    .table-form {
        width: 100%;
        margin-bottom: 30px;
    }
    .table-form td {
        padding: 0 1px 0 0;
        vertical-align: top;
    }
    .table-form td input, .table-form td select {
        width: 100%;
        height: auto;
        border: solid 1px #ecf0f1;
        border-radius: 4px;
        padding: 3px 4px;
    }
    .table-form td select {
        padding: 1px 4px;
    }
    .table-form .top-content td {
        font-size: inherit;
        vertical-align: middle;
    }
    .table-form .top-content input, .table-form .top-content select {
        font-size: inherit;
    }
    .table-form .middle-label td {
        text-align: center;
        font-weight: bold;
        font-size: 12px;
    }
    .table-form .middle-label .type td {
        font-weight: normal;
        font-size: 11px;
    }
    .table-form .middle-content input, .table-form .low-content input, .table-form .middle-content select, .table-form .low-content select {
        font-size: 11px;
    }
    .table-form .total {
        border-top: 1px solid #000;
    }
    .table-form .total td {
        font-weight: bold;
    }
    .table-form .low-content td {
        padding-top: 3px;
        padding-bottom: 40px;
    }
    .table-form .sep td {
        padding-bottom: 3px;
    }
    .table-form .grand-total {
        border-top: 3px solid #000;
    }
    .table-form .grand-total td {
        font-weight: bold;
        font-size: 16px;
        padding-top: 3px;
    }
</style>

<div class="panel panel-default">
    <div class="panel-body">
        <table class="table-form">
            <thead class="middle-label">
            <tr>
                <td>Popis</td>
                <td>Částka</td>
                <td></td>
            </tr>
            </thead>
            <tbody>
            {% for entity in entities %}
                <tr>

                    <td>
                        <input style="margin-bottom: 1px;" type="text" readonly="readonly" value="{{ entity.description }}">
                    </td>
                    <td>
                        <input style="margin-bottom: 1px;" type="text" readonly="readonly" value="{{ entity.price|number_format(0, ',', ' ') }}">
                    </td>
                    <td class="text-right">
                        <a title="Odstranit" style='margin-left: 5px' class="btn btn-xs btn-danger" href="{{ path('app_invoice_delete', {'invoiceItem_id': entity.id}) }}">
                            <i class="fa fa-fw fa-trash"></i>
                        </a>
                    </td>
                </tr>

            {% endfor %}
            </tbody>
            <tbody class="sep">
            <tr>
                <td colspan="3">
                    <a class="btn btn-xs btn-default" title="nová položka" href="{{ path('app_invoice_create', {'commission_id' : commission.data.id}) }}">
                        <i class="fa fa-fw fa-plus"></i> nová položka
                    </a>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr class="grand-total">
                <td colspan="1">SOUČET</td>
                <td class="cell-sumSellingPriceReal">
                    <input type="text" class="form-control" readonly="readonly" value="{{ commission2.invoiceItemsSum }}">
                </td>
                <td></td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock %}

src/AppBundle/Resources/views/Invoice/update.html.twig
{% extends "::layout-secured-simple.html.twig" %}
{% set title = "Úprava položky k fakturaci pro " ~ commission.name %}
{% block title %}{{ title }} {{ titleSeparator }} {{ parent() }}{% endblock %}
{% block body_class %}page-budget-update {{ parent() }}{% endblock %}

{% block content %}


        <div class="row">

            <div class="col-lg-12">
                <a class="btn btn-info" title="Zpět" href="{{ path('app_invoice_list', {'commission_id': commission.id}) }}"><i class="fa fa-fw fa-caret-left"></i> Zpět</a>

                <div class="page-header text-center">
                    <h2><i class="fa fa-fw fa-money"></i> {{ title }}</h2>
                </div>
            </div> <!-- .col-lg-12 -->


            {% include "@App/Invoice/inc/form.html.twig" with {"form" : form, "submitLabel" : "Uložit"} %}



        </div> <!-- .row -->


{% endblock %}